lint:
  min-version: v0.12.0
  formatter: default
  rules:
    - header-min-length
    - header-max-length
    - body-max-line-length
    - footer-max-line-length
    - type-enum
  severity:
    default: error
    rules: {}
  settings:
    body-max-line-length:
      argument: 100
      flags: {}
    footer-max-line-length:
      argument: 100
      flags: {}
    header-max-length:
      argument: 72
      flags: {}
    header-min-length:
      argument: 10
      flags: {}
    type-enum:
      argument:
        - feat
        - fix
        - docs
        - style
        - refactor
        - perf
        - test
        - build
        - ci
        - chore
        - revert
      flags: {}
  disable-default-ignores: false
  ignores: []
changelog:
  formatter: markdown
  output: ""
  header: "# Changelog"
  repository:
    url: ""
    commit-url: ""
    compare-url: ""
  issue-prefixes:
    - "#"
  include-other: false
  include-breaking: true
  skip-merge-commits: true
  types:
    - type: feat
      header: Features
      hidden: false
    - type: fix
      header: Bug Fixes
      hidden: false
    - type: docs
      header: Documentation
      hidden: false
    - type: perf
      header: Performance
      hidden: false
