// Code generated by qtc from "template.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line template.qtpl:1
package commitlint

//line template.qtpl:3
import (
	"github.com/conventionalcommit/parser"
)

//line template.qtpl:7
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line template.qtpl:7
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line template.qtpl:7
func streamerrorMessage(qw422016 *qt422016.Writer, cMsg *parser.Commit, res *Result) {
//line template.qtpl:7
	qw422016.N().S(`commitlint

  → input: `)
//line template.qtpl:10
	qw422016.N().Q(cMsg.FullCommit)
//line template.qtpl:10
	qw422016.N().S(`

`)
//line template.qtpl:12
	if res.HasErrors() {
//line template.qtpl:12
		qw422016.N().S(`Errors:
`)
//line template.qtpl:14
		for _, msg := range res.Errors() {
//line template.qtpl:14
			qw422016.N().S(`  ❌ `)
//line template.qtpl:15
			qw422016.N().S(msg)
//line template.qtpl:15
			qw422016.N().S(`
`)
//line template.qtpl:16
		}
//line template.qtpl:17
	}
//line template.qtpl:17
	qw422016.N().S(`
`)
//line template.qtpl:19
	if res.HasWarns() {
//line template.qtpl:19
		qw422016.N().S(`Warnings:
`)
//line template.qtpl:21
		for _, msg := range res.Warns() {
//line template.qtpl:21
			qw422016.N().S(`  ❌ `)
//line template.qtpl:22
			qw422016.N().S(msg)
//line template.qtpl:22
			qw422016.N().S(`
`)
//line template.qtpl:23
		}
//line template.qtpl:24
	}
//line template.qtpl:24
	qw422016.N().S(`
Total `)
//line template.qtpl:26
	qw422016.N().D(len(res.Errors()))
//line template.qtpl:26
	qw422016.N().S(` errors, `)
//line template.qtpl:26
	qw422016.N().D(len(res.Warns()))
//line template.qtpl:26
	qw422016.N().S(` warnings
`)
//line template.qtpl:27
}

//line template.qtpl:27
func writeerrorMessage(qq422016 qtio422016.Writer, cMsg *parser.Commit, res *Result) {
//line template.qtpl:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:27
	streamerrorMessage(qw422016, cMsg, res)
//line template.qtpl:27
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:27
}

//line template.qtpl:27
func errorMessage(cMsg *parser.Commit, res *Result) string {
//line template.qtpl:27
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:27
	writeerrorMessage(qb422016, cMsg, res)
//line template.qtpl:27
	qs422016 := string(qb422016.B)
//line template.qtpl:27
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:27
	return qs422016
//line template.qtpl:27
}

//line template.qtpl:29
func streamsuccessMessage(qw422016 *qt422016.Writer, cMsg *parser.Commit, res *Result) {
//line template.qtpl:29
	qw422016.N().S(` ✓ commit message
`)
//line template.qtpl:31
}

//line template.qtpl:31
func writesuccessMessage(qq422016 qtio422016.Writer, cMsg *parser.Commit, res *Result) {
//line template.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:31
	streamsuccessMessage(qw422016, cMsg, res)
//line template.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:31
}

//line template.qtpl:31
func successMessage(cMsg *parser.Commit, res *Result) string {
//line template.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:31
	writesuccessMessage(qb422016, cMsg, res)
//line template.qtpl:31
	qs422016 := string(qb422016.B)
//line template.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:31
	return qs422016
//line template.qtpl:31
}

//line template.qtpl:33
func StreamCommitMsgHook(qw422016 *qt422016.Writer) {
//line template.qtpl:33
	qw422016.N().S(`#!/bin/sh

commitlint lint --msg $1
`)
//line template.qtpl:37
}

//line template.qtpl:37
func WriteCommitMsgHook(qq422016 qtio422016.Writer) {
//line template.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line template.qtpl:37
	StreamCommitMsgHook(qw422016)
//line template.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line template.qtpl:37
}

//line template.qtpl:37
func CommitMsgHook() string {
//line template.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line template.qtpl:37
	WriteCommitMsgHook(qb422016)
//line template.qtpl:37
	qs422016 := string(qb422016.B)
//line template.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line template.qtpl:37
	return qs422016
//line template.qtpl:37
}
