// Code generated by qtc from "hook.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

package hook

import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

func streamcommitMsgHook(qw422016 *qt422016.Writer) {
	qw422016.N().S(`#!/bin/sh

commitlint lint --message $1
`)
}

func writecommitMsgHook(qq422016 qtio422016.Writer) {
	qw422016 := qt422016.AcquireWriter(qq422016)
	streamcommitMsgHook(qw422016)
	qt422016.ReleaseWriter(qw422016)
}

func commitMsgHook() string {
	qb422016 := qt422016.AcquireByteBuffer()
	writecommitMsgHook(qb422016)
	qs422016 := string(qb422016.B)
	qt422016.ReleaseByteBuffer(qb422016)
	return qs422016
}
