package config

import (
	"github.com/conventionalcommit/commitlint/formatter"
	"github.com/conventionalcommit/commitlint/internal"
	"github.com/conventionalcommit/commitlint/lint"
	"github.com/conventionalcommit/commitlint/rule"
)

const (
	DefaultTypeCharset  = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
	DefaultScopeCharset = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ/,"
)

// DefaultIgnorePatterns returns the default list of ignore patterns
// These patterns match commit messages auto-generated by git commands
// like merge, revert, fixup, squash, etc.
func DefaultIgnorePatterns() []string {
	return []string{
		// GitHub / GitLab merge
		`^Merge pull request #\d+`,
		`^Merge .+ into .+`,
		`^Merge branch '.+'`,
		`^Merge tag '.+'`,
		`^Merge remote-tracking branch '.+'`,

		// Azure DevOps / Bitbucket merge
		`^Merged .+ (in|into) .+`,
		`^Merged PR #?\d+`,

		// Revert and Reapply
		`^(R|r)evert `,
		`^(R|r)eapply `,

		// Fixup, Amend, Squash (git commit --fixup/--squash)
		`^(amend|fixup|squash)! `,

		// Automatic merges
		`^Automatic merge`,
		`^Auto-merged .+ into .+`,

		// Initial commit
		`^Initial commit$`,
	}
}

// DefaultTypeEnums returns the default list of type enums
func DefaultTypeEnums() []interface{} {
	return []interface{}{
		"feat", "fix", "docs", "style", "refactor", "perf",
		"test", "build", "ci", "chore", "revert",
	}
}

// NewDefault returns default config
func NewDefault() *lint.Config {
	// Enabled Rules
	rules := []string{
		(&rule.HeadMinLenRule{}).Name(),
		(&rule.HeadMaxLenRule{}).Name(),
		(&rule.BodyMaxLineLenRule{}).Name(),
		(&rule.FooterMaxLineLenRule{}).Name(),
		(&rule.TypeEnumRule{}).Name(),
	}

	// Severity Levels
	severity := lint.SeverityConfig{
		Default: lint.SeverityError,
	}

	// Default Rule Settings
	settings := map[string]lint.RuleSetting{
		// Header Min Len Rule
		(&rule.HeadMinLenRule{}).Name(): {
			Argument: 10,
		},

		// Header Max Len Rule
		(&rule.HeadMaxLenRule{}).Name(): {
			Argument: 72,
		},

		// Body Max Line Rule
		(&rule.BodyMaxLineLenRule{}).Name(): {
			Argument: 100,
		},

		// Footer Max Line Rule
		(&rule.FooterMaxLineLenRule{}).Name(): {
			Argument: 100,
		},

		// Types Enum Rule
		(&rule.TypeEnumRule{}).Name(): {
			Argument: DefaultTypeEnums(),
		},

		// Scope Enum Rule
		(&rule.ScopeEnumRule{}).Name(): {
			Argument: []interface{}{},
			Flags: map[string]interface{}{
				"allow-empty": true,
			},
		},

		// Body Min Len Rule
		(&rule.BodyMinLenRule{}).Name(): {
			Argument: 0,
		},

		// Body Max Len Rule
		(&rule.BodyMaxLenRule{}).Name(): {
			Argument: -1,
		},

		// Footer Min Len Rule
		(&rule.FooterMinLenRule{}).Name(): {
			Argument: 0,
		},

		// Footer Max Len Rule
		(&rule.FooterMaxLenRule{}).Name(): {
			Argument: -1,
		},

		// Type Min Len Rule
		(&rule.TypeMinLenRule{}).Name(): {
			Argument: 0,
		},

		// Type Max Len Rule
		(&rule.TypeMaxLenRule{}).Name(): {
			Argument: -1,
		},

		// Scope Min Len Rule
		(&rule.ScopeMinLenRule{}).Name(): {
			Argument: 0,
		},

		// Scope Max Len Rule
		(&rule.ScopeMaxLenRule{}).Name(): {
			Argument: -1,
		},

		// Description Min Len Rule
		(&rule.DescriptionMinLenRule{}).Name(): {
			Argument: 0,
		},

		// Description Max Len Rule
		(&rule.DescriptionMaxLenRule{}).Name(): {
			Argument: -1,
		},

		// Type Charset Rule
		(&rule.TypeCharsetRule{}).Name(): {
			Argument: DefaultTypeCharset,
		},

		// Scope Charset Rule
		(&rule.ScopeCharsetRule{}).Name(): {
			Argument: DefaultScopeCharset,
		},

		// Footer Enum Rule
		(&rule.FooterEnumRule{}).Name(): {
			Argument: []interface{}{},
		},

		// Footer Type Enum Rule
		(&rule.FooterTypeEnumRule{}).Name(): {
			Argument: []interface{}{},
		},

		// Case Rules
		(&rule.TypeCaseRule{}).Name(): {
			Argument: "lower-case",
		},
		(&rule.ScopeCaseRule{}).Name(): {
			Argument: "lower-case",
		},
		(&rule.DescriptionCaseRule{}).Name(): {
			Argument: "lower-case",
		},
		(&rule.BodyCaseRule{}).Name(): {
			Argument: "lower-case",
		},
		(&rule.HeaderCaseRule{}).Name(): {
			Argument: "lower-case",
		},

		// Full-stop Rules
		(&rule.HeaderFullStopRule{}).Name(): {
			Argument: ".",
		},
		(&rule.BodyFullStopRule{}).Name(): {
			Argument: ".",
		},
		(&rule.DescriptionFullStopRule{}).Name(): {
			Argument: ".",
		},

		// Trailer / Signed-off-by
		(&rule.SignedOffByRule{}).Name(): {
			Argument: "Signed-off-by",
		},
		(&rule.TrailerExistsRule{}).Name(): {
			Argument: "Signed-off-by",
		},

		// Empty rules (no argument needed)
		(&rule.TypeEmptyRule{}).Name():        {},
		(&rule.ScopeEmptyRule{}).Name():       {},
		(&rule.BodyEmptyRule{}).Name():        {},
		(&rule.FooterEmptyRule{}).Name():      {},
		(&rule.DescriptionEmptyRule{}).Name(): {},

		// Leading-blank rules (no argument needed)
		(&rule.BodyLeadingBlankRule{}).Name():   {},
		(&rule.FooterLeadingBlankRule{}).Name(): {},

		// Header trim (no argument needed)
		(&rule.HeaderTrimRule{}).Name(): {},

		// Breaking change (no argument needed)
		(&rule.BreakingChangeExclamationMarkRule{}).Name(): {},
	}

	def := &lint.Config{
		MinVersion:            internal.Version(),
		Formatter:             (&formatter.DefaultFormatter{}).Name(),
		Rules:                 rules,
		Severity:              severity,
		Settings:              settings,
		DefaultIgnorePatterns: DefaultIgnorePatterns(),
	}
	return def
}
