name: Go

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
    types:
      - opened
      - synchronize
      - reopened
      - review_requested
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24.2"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
